repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict


-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        exclude: __init__.py
        args: [--py310-plus]

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8
        exclude: __init__.py

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: __init__.py
        args: [ "--ignore=E501" ]


# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v0.902
#     hooks:
#       - id: mypy
#         exclude: ^tests/
#         args: [--strict]
