version: "3.8"
services:
  test:
    container_name: api_test
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # environment:
    #   - TEST=1
    entrypoint: >
      sh -c "
        python -m alembic upgrade head
        python -m pytest -vv
      "
    networks:
      - api_test
    ports:
      - "8000:8000"
    depends_on:
      test_db:
        condition: service_healthy
      redis:
        condition: service_healthy
  test_db:
    container_name: "tests_db"
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre22
      #- POSTGRES_DB=python_db
      - POSTGRES_DB=test_db
    expose:
      - 5432
    networks:
      - api_test
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 20s
      retries: 100
  redis:
    container_name: "redis_cache"
    image: redis:7-alpine
    environment:
      - REDIS_PORT=6379
    networks:
      - api_test
    expose:
      - 6379
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100
networks:
  api_test:
    driver: bridge
