version: "3.8"
services:
  api:
    container_name: FastAPI_Menu
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: >
      sh -c "
        python -m alembic upgrade head
        uvicorn main:app --host 0.0.0.0 --reload
      "
    networks:
      - FastAPI_Menu
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: "postgre_db"
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgre22
      - POSTGRES_DB=python_db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - FastAPI_Menu
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 20s
      retries: 100
networks:
  FastAPI_Menu:
    driver: bridge